import pytest
from money import Money

from part.constants import (
    SOURCE_ACURAEXPRESSPARTS,
    SOURCE_ACURAPARTSFORLESS,
    SOURCE_AKR,
    SOURCE_ALL4HONDA,
    SOURCE_AMAYAMA,
    SOURCE_CMS,
    SOURCE_HONDAAUTOMOTIVEPARTS,
    SOURCE_HONDAPARTSNOW,
    SOURCE_HONDAPARTSONLINE,
    SOURCE_HONDASPAREPARTS,
    SOURCE_NENGUN,
    SOURCE_ONLINETEILE,
    SOURCE_PIECESAUTOHONDA,
    SOURCE_TEGIWA,
)
from scrapper.clients.acuraexpressparts import AcuraexpresspartsClient
from scrapper.clients.acurapartsforless import AcurapartsforlessClient
from scrapper.clients.akr import AkrClient
from scrapper.clients.all4honda import All4hondaClient
from scrapper.clients.amayama import AmayamaClient
from scrapper.clients.cms import CmsClient
from scrapper.clients.hondaautomotiveparts import HondaautomotivepartsClient
from scrapper.clients.hondapartsnow import HondapartsnowClient
from scrapper.clients.hondapartsonline import HondapartsonlineClient
from scrapper.clients.hondaspareparts import HondasparepartsClient
from scrapper.clients.nengun import NengunClient
from scrapper.clients.onlineteile import OnlineteileClient
from scrapper.clients.piecesautohonda import PiecesAutoHondaClient
from scrapper.clients.tegiwa import TegiwaClient
from scrapper.common.stock import Stock

REFERENCES = {
    "12251-RBB-004",  # normal part
    "74100-S2A-010",  # normal part
    "56483-PND-003",  # discontinued part but has new replacement
    "08F03-S02-180K",  # really discontinued part
    "31206-P3F-003",  # sold out in some sites
}


@pytest.mark.asyncio
@pytest.mark.vcr()
class TestClients:
    @pytest.mark.parametrize(
        "client, expected",
        (
            (
                HondapartsnowClient(),
                {
                    "12251-RBB-004": Stock(
                        available=True,
                        reference="12251-RBB-004",
                        price=Money(amount="102.08", currency="USD"),
                        title="Gasket, Cylinder Head (Nippon LEAkless)",
                        discontinued=False,
                        image="https://www.hondapartsnow.com/resources/encry/actual-picture/hpn/large/a5254ccaa3be7c7eb2b12f5745f04ca0/93bd5a06e83c3a33c1985cee27354789.jpg",
                        url="https://www.hondapartsnow.com/genuine/honda~gasket~cylinder~head~12251-rbb-004.html",
                        country="US",
                        source=SOURCE_HONDAPARTSNOW,
                    ),
                    "56483-PND-003": Stock(
                        available=False,
                        reference="56483-PND-003",
                        price=Money(amount="15.68", currency="USD"),
                        title="Pulley, Power Steering Pump",
                        discontinued=True,
                        image="https://www.hondapartsnow.com/resources/encry/part-picture/hpn/large/792b87b040876fda9770fd4a712d9665/756566f6e674b120a1c138fcb821a53c.png",
                        url="https://www.hondapartsnow.com/genuine/honda~pulley~power~steering~56483-pnd-003.html",
                        country="US",
                        source=SOURCE_HONDAPARTSNOW,
                    ),
                    "08F03-S02-180K": Stock(
                        available=False,
                        reference="08F03-S02-180K",
                        price=Money(amount="211.75", currency="USD"),
                        title="Spoiler, Rear Under (Vogue Silver Metallic)",
                        discontinued=True,
                        image=None,
                        url="https://www.hondapartsnow.com/genuine/honda~spoiler~08f03-s02-180k.html",
                        country="US",
                        source=SOURCE_HONDAPARTSNOW,
                    ),
                    "31206-P3F-003": Stock(
                        reference="31206-P3F-003",
                        url="https://www.hondapartsnow.com/genuine/honda~armature~31206-p3f-003.html",
                        source=SOURCE_HONDAPARTSNOW,
                        country="US",
                        title="Armature",
                        price=Money("365.23", "USD"),
                        image="https://www.hondapartsnow.com/resources/encry/part-picture/hpn/large/5045e7403da1abdff6fb3bebadf2b54b/8e3ec15302dc4429b6427e73d6984b06.png",
                        available=False,
                        discontinued=True,
                        quantity=None,
                    ),
                    "74100-S2A-010": Stock(
                        reference="74100-S2A-010",
                        url="https://www.hondapartsnow.com/genuine/honda~fender~assy~74100-s2a-010.html",
                        source=SOURCE_HONDAPARTSNOW,
                        country="US",
                        title="Fender Assembly, Right Front (Inner)",
                        price=Money("106.40", "USD"),
                        image="https://www.hondapartsnow.com/resources/encry/actual-picture/hpn/large/3b265650f5462cf45574014c7ca271fb/dfa5952adefb34667c0c1998b86c9200.jpg",
                        available=True,
                        discontinued=False,
                        quantity=None,
                    ),
                },
            ),
            (
                HondapartsonlineClient(),
                {
                    "12251-RBB-004": Stock(
                        available=True,
                        reference="12251-RBB-004",
                        price=Money(amount="107.23", currency="USD"),
                        title="Gasket, Cylinder Head (Nippon Leakless) - Honda (12251-RBB-004)",
                        discontinued=False,
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/7cfd97ab6173d165e37dec41c6a978e9/85957d0bd63c58860e15bdc7b79afe4f.gif",
                        url="https://www.hondapartsonline.net/oem-parts/honda-gasket-cylinder-head-nippon-leakless-12251rbb004",
                        country="US",
                        source=SOURCE_HONDAPARTSONLINE,
                    ),
                    "56483-PND-003": Stock(
                        available=False,
                        reference="56483-PND-003",
                        price=Money(amount="16.48", currency="USD"),
                        title="Pulley, Power Steering Pump - Honda (56483-PND-003)",
                        discontinued=True,
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/056442089e514a4e09f554927e3d604f/7e1bbfa7e632ddb91eb5f5bb58518895.png",
                        url="https://www.hondapartsonline.net/oem-parts/honda-pulley-power-steering-pump-56483pnd003",
                        country="US",
                        source=SOURCE_HONDAPARTSONLINE,
                    ),
                    "08F03-S02-180K": Stock(
                        available=False,
                        reference="08F03-S02-180K",
                        price=Money(amount="220.58", currency="USD"),
                        title="Spoiler, Rear Under *NH583M* (Vogue Silver Metallic) - Honda (08F03-S02-180K)",
                        discontinued=True,
                        image="https://s3.amazonaws.com/static.revolutionparts.com/assets/images/honda.png",
                        url="https://www.hondapartsonline.net/oem-parts/honda-spoiler-rear-under-nh583m-vogue-silver-metallic-08f03s02180k",
                        country="US",
                        source=SOURCE_HONDAPARTSONLINE,
                    ),
                    "31206-P3F-003": Stock(
                        reference="31206-P3F-003",
                        url="https://www.hondapartsonline.net/oem-parts/honda-armature-31206p3f003",
                        source=SOURCE_HONDAPARTSONLINE,
                        country="US",
                        title="Armature - Honda (31206-P3F-003)",
                        price=Money(amount="380.45", currency="USD"),
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/9975b81af67056cae80ebf24ef8b639c/e20c8f426e887da8ac3ec1522cd66c31.gif",
                        available=True,
                        discontinued=False,
                        quantity=None,
                    ),
                    "74100-S2A-010": Stock(
                        reference="74100-S2A-010",
                        url="https://www.hondapartsonline.net/oem-parts/honda-fender-assembly-r-front-inner-74100s2a010",
                        source=SOURCE_HONDAPARTSONLINE,
                        country="US",
                        title="Fender Assembly, R Front (Inner) - Honda (74100-S2A-010)",
                        price=Money(amount="111.76", currency="USD"),
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/15e978bce0ad5c894ee495fee5c38985/b4a6e695c020ba70dea25395b7a487d6.png",
                        available=True,
                        discontinued=False,
                        quantity=None,
                    ),
                },
            ),
            (
                HondaautomotivepartsClient(),
                {
                    "12251-RBB-004": Stock(
                        available=True,
                        reference="12251-RBB-004",
                        price=Money(amount="98.65", currency="USD"),
                        title="Gasket, Cylinder Head (Nippon Leakless) - Honda (12251-RBB-004)",
                        discontinued=False,
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/7cfd97ab6173d165e37dec41c6a978e9/85957d0bd63c58860e15bdc7b79afe4f.gif",
                        url="https://www.hondaautomotiveparts.com/oem-parts/honda-gasket-cylinder-head-nippon-leakless-12251rbb004",
                        country="US",
                        source=SOURCE_HONDAAUTOMOTIVEPARTS,
                    ),
                    "56483-PND-003": Stock(
                        available=False,
                        reference="56483-PND-003",
                        price=Money(amount="15.82", currency="USD"),
                        title="Pulley, Power Steering Pump - Honda (56483-PND-003)",
                        discontinued=True,
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/056442089e514a4e09f554927e3d604f/7e1bbfa7e632ddb91eb5f5bb58518895.png",
                        url="https://www.hondaautomotiveparts.com/oem-parts/honda-pulley-power-steering-pump-56483pnd003",
                        country="US",
                        source=SOURCE_HONDAAUTOMOTIVEPARTS,
                    ),
                    "08F03-S02-180K": Stock(
                        available=False,
                        reference="08F03-S02-180K",
                        price=Money(amount="197.64", currency="USD"),
                        title="Spoiler, Rear Under *NH583M* (Vogue Silver Metallic) - Honda (08F03-S02-180K)",
                        discontinued=True,
                        image="https://s3.amazonaws.com/static.revolutionparts.com/assets/images/honda.png",
                        url="https://www.hondaautomotiveparts.com/oem-parts/honda-spoiler-rear-under-nh583m-vogue-silver-metallic-08f03s02180k",
                        country="US",
                        source=SOURCE_HONDAAUTOMOTIVEPARTS,
                    ),
                    "31206-P3F-003": Stock(
                        reference="31206-P3F-003",
                        url="https://www.hondaautomotiveparts.com/oem-parts/honda-armature-31206p3f003",
                        source=SOURCE_HONDAAUTOMOTIVEPARTS,
                        country="US",
                        title="Armature - Honda (31206-P3F-003)",
                        price=Money("340.88", currency="USD"),
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/9975b81af67056cae80ebf24ef8b639c/e20c8f426e887da8ac3ec1522cd66c31.gif",
                        available=True,
                        discontinued=False,
                        quantity=None,
                    ),
                    "74100-S2A-010": Stock(
                        reference="74100-S2A-010",
                        url="https://www.hondaautomotiveparts.com/oem-parts/honda-fender-assembly-r-front-inner-74100s2a010",
                        source=SOURCE_HONDAAUTOMOTIVEPARTS,
                        country="US",
                        title="Fender Assembly, R Front (Inner) - Honda (74100-S2A-010)",
                        price=Money("102.82", currency="USD"),
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/15e978bce0ad5c894ee495fee5c38985/b4a6e695c020ba70dea25395b7a487d6.png",
                        available=True,
                        discontinued=False,
                        quantity=None,
                    ),
                },
            ),
            (
                TegiwaClient(),
                {
                    "12251-RBB-004": Stock(
                        available=False,
                        reference="12251-RBB-004",
                        price=Money(amount="65", currency="GBP"),
                        title="GENUINE HONDA HEAD GASKET K-SERIES K24",
                        discontinued=None,
                        url="https://www.tegiwaimports.com/genuine-honda-head-gasket-k-series-k24.html",
                        image="https://www.tegiwaimports.com/media/catalog/product/cache/1/image/470x470/4be6a58e18b1f94a8adc93cd75a4b5ce/g/e/genuine-honda-head-gasket-k-series_2.jpg",
                        country="GB",
                        source=SOURCE_TEGIWA,
                    ),
                    "56483-PND-003": None,
                    "08F03-S02-180K": None,
                    "31206-P3F-003": None,
                    "74100-S2A-010": None,
                },
            ),
            (
                HondasparepartsClient(),
                {
                    "12251-RBB-004": Stock(
                        available=True,
                        reference="12251-RBB-004",
                        price=Money(amount="89.11", currency="GBP"),
                        title="GASKET COMP., CYLINDER HE",
                        discontinued=None,
                        url="https://hondaspareparts.co.uk/products/12251RBB004",
                        country="GB",
                        source=SOURCE_HONDASPAREPARTS,
                    ),
                    "56483-PND-003": Stock(
                        available=True,
                        reference="56483-PND-003",
                        price=Money(amount="74.47", currency="GBP"),
                        title="PULLEY COMP., POWER STEER",
                        discontinued=None,
                        url="https://hondaspareparts.co.uk/products/56483PND003",
                        country="GB",
                        source=SOURCE_HONDASPAREPARTS,
                    ),
                    "08F03-S02-180K": None,
                    "31206-P3F-003": Stock(
                        available=False,
                        reference="31206-P3F-003",
                        price=Money(amount="0.00", currency="GBP"),
                        title="ARMATURE COMP. (###)",
                        discontinued=None,
                        url="https://hondaspareparts.co.uk/products/31206P3F003",
                        country="GB",
                        source=SOURCE_HONDASPAREPARTS,
                    ),
                    "74100-S2A-010": Stock(
                        reference="74100-S2A-010",
                        url="https://hondaspareparts.co.uk/products/74100S2A010",
                        source=SOURCE_HONDASPAREPARTS,
                        country="GB",
                        title="FENDER ASSY., R. FR. INNE",
                        price=Money(amount="145.05", currency="GBP"),
                        image=None,
                        available=True,
                        discontinued=None,
                        quantity=None,
                    ),
                },
            ),
            (
                PiecesAutoHondaClient(),
                {
                    "12251-RBB-004": Stock(
                        reference="12251-RBB-004",
                        url="https://www.pieces-auto-honda.fr/honda-voiture/affectation_pieces_detachees/12251RBB004",
                        source=SOURCE_PIECESAUTOHONDA,
                        country="FR",
                        title="Joint comp. de culasse (n",
                        price=Money(amount="90.76", currency="EUR"),
                        image=None,
                        available=True,
                        discontinued=False,
                        quantity=None,
                    ),
                    "56483-PND-003": Stock(
                        reference="56483-PND-003",
                        url="https://www.pieces-auto-honda.fr/honda-voiture/affectation_pieces_detachees/56483PND003",
                        source=SOURCE_PIECESAUTOHONDA,
                        country="FR",
                        title="Poulie de pompe a directi",
                        price=None,
                        image=None,
                        available=False,
                        discontinued=True,
                        quantity=None,
                    ),
                    "08F03-S02-180K": None,
                    "31206-P3F-003": Stock(
                        reference="31206-P3F-003",
                        url="https://www.pieces-auto-honda.fr/honda-voiture/affectation_pieces_detachees/31206P3F003",
                        source=SOURCE_PIECESAUTOHONDA,
                        country="FR",
                        title="Induit comp.",
                        price=None,
                        image=None,
                        available=False,
                        discontinued=False,
                        quantity=None,
                    ),
                    "74100-S2A-010": Stock(
                        reference="74100-S2A-010",
                        url="https://www.pieces-auto-honda.fr/honda-voiture/affectation_pieces_detachees/74100S2A010",
                        source=SOURCE_PIECESAUTOHONDA,
                        country="FR",
                        title="Ens. garde-boue interieur",
                        price=Money(amount="186.5", currency="EUR"),
                        image=None,
                        available=True,
                        discontinued=False,
                        quantity=None,
                    ),
                },
            ),
            (
                AmayamaClient(),
                {
                    "12251-RBB-004": [
                        Stock(
                            reference="12251-RBB-004",
                            url="https://www.amayama.com/en/part/honda/12251rbb004",
                            source=SOURCE_AMAYAMA,
                            country="JP",
                            title="GASKET COMP., CYLINDER HEAD (NIPPON LEAKLESS)",
                            price=Money(amount="49.41", currency="USD"),
                            image="https://static.amayama.com/part/honda-12251rbb004-1561012265107-big.jpg",
                            available=True,
                            discontinued=None,
                            quantity=None,
                        ),
                        Stock(
                            reference="12251-RBB-004",
                            url="https://www.amayama.com/en/part/honda/12251rbb004",
                            source=SOURCE_AMAYAMA,
                            country="AE",
                            title="GASKET COMP., CYLINDER HEAD (NIPPON LEAKLESS)",
                            price=Money(amount="67.86", currency="USD"),
                            image="https://static.amayama.com/part/honda-12251rbb004-1561012265107-big.jpg",
                            available=True,
                            discontinued=None,
                            quantity=26,
                        ),
                    ],
                    "56483-PND-003": [
                        Stock(
                            reference="56483-PND-003",
                            url="https://www.amayama.com/en/part/honda/56483pnd003",
                            source=SOURCE_AMAYAMA,
                            country="JP",
                            title="PULLEY COMP., POWER STEERING PUMP",
                            price=Money(amount="28.66", currency="USD"),
                            image="https://static.amayama.com/schema/honda-56483pnd003-1568785753036-big.jpg",
                            available=True,
                            discontinued=None,
                            quantity=None,
                        )
                    ],
                    "08F03-S02-180K": None,
                    "31206-P3F-003": [
                        Stock(
                            reference="31206-P3F-003",
                            url="https://www.amayama.com/en/part/honda/31206p3f003",
                            source=SOURCE_AMAYAMA,
                            country="JP",
                            title="ARMATURE COMP.",
                            price=Money(amount="199.45", currency="USD"),
                            image="https://static.amayama.com/schema/honda-31206p3f003-1568726492705-big.jpg",
                            available=True,
                            discontinued=None,
                            quantity=None,
                        )
                    ],
                    "74100-S2A-010": [
                        Stock(
                            reference="74100-S2A-010",
                            url="https://www.amayama.com/en/part/honda/74100s2a010",
                            source=SOURCE_AMAYAMA,
                            country="JP",
                            title="FENDER ASSY., R. FR. INNER",
                            price=Money(amount="76.70", currency="USD"),
                            image="https://static.amayama.com/schema/honda-74100s2a010-1568746841881-big.jpg",
                            available=True,
                            discontinued=None,
                            quantity=None,
                        )
                    ],
                },
            ),
            (
                AcuraexpresspartsClient(),
                {
                    "12251-RBB-004": Stock(
                        reference="12251-RBB-004",
                        url="https://www.acuraexpressparts.com/oem-parts/acura-gasket-cylinder-head-nippon-leakless-12251rbb004",
                        source=SOURCE_ACURAEXPRESSPARTS,
                        country="US",
                        title="Gasket, Cylinder Head (Nippon Leakless) - Acura (12251-RBB-004)",
                        price=Money(amount="102.94", currency="USD"),
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/7b1561c8a4029868d71075924f0861c2/8d93926db7f69e26349268f245817c37.gif",
                        available=True,
                        discontinued=False,
                        quantity=None,
                    ),
                    "56483-PND-003": Stock(
                        reference="56483-PND-003",
                        url="https://www.acuraexpressparts.com/oem-parts/acura-pulley-power-steering-pump-56483pnd003",
                        source=SOURCE_ACURAEXPRESSPARTS,
                        country="US",
                        title="Pulley, Power Steering Pump - Acura (56483-PND-003)",
                        price=Money(amount="16.21", currency="USD"),
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/c698a571f74957bb119a8b945bf3250e/48c7fcef179369ce2d238f7e80e095ef.gif",
                        available=False,
                        discontinued=True,
                        quantity=None,
                    ),
                    "08F03-S02-180K": None,
                    "31206-P3F-003": None,
                    "74100-S2A-010": None,
                },
            ),
            (
                All4hondaClient(),
                {
                    "12251-RBB-004": Stock(
                        country="NL",
                        reference="12251-RBB-004",
                        url="https://www.a4h-tech.com/en/oem-honda-head-gasket-accord-2003-2012-2-4-type-s",
                        source=SOURCE_ALL4HONDA,
                        title="OEM Honda head gasket (Accord 2003-2012 2.4 type S)",
                        price=Money(amount="112.95", currency="EUR"),
                        image="https://www.a4h-tech.com/media/catalog/product/cache/3558329f726a95ba08740a57c013e49b/1/2/12251-rbb-004-oem-honda-koppakking-accord-2003-2012-2.4-type-s-all4honda.jpg",
                    ),
                    "56483-PND-003": None,
                    "08F03-S02-180K": None,
                    "31206-P3F-003": None,
                    "74100-S2A-010": None,
                },
            ),
            (
                AcurapartsforlessClient(),
                {
                    "12251-RBB-004": Stock(
                        available=True,
                        reference="12251-RBB-004",
                        price=Money(amount="102.08", currency="USD"),
                        title="Gasket, Cylinder Head (Nippon Leakless) - Acura (12251-RBB-004)",
                        discontinued=False,
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/7b1561c8a4029868d71075924f0861c2/8d93926db7f69e26349268f245817c37.gif",
                        url="https://www.acurapartsforless.com/oem-parts/acura-gasket-cylinder-head-nippon-leakless-12251rbb004",
                        country="US",
                        source=SOURCE_ACURAPARTSFORLESS,
                    ),
                    "56483-PND-003": Stock(
                        available=False,
                        reference="56483-PND-003",
                        price=Money(amount="17", currency="USD"),
                        title="Pulley, Power Steering Pump - Acura (56483-PND-003)",
                        discontinued=True,
                        image="https://dz310nzuyimx0.cloudfront.net/strapr1/c698a571f74957bb119a8b945bf3250e/48c7fcef179369ce2d238f7e80e095ef.gif",
                        url="https://www.acurapartsforless.com/oem-parts/acura-pulley-power-steering-pump-56483pnd003",
                        country="US",
                        source=SOURCE_ACURAPARTSFORLESS,
                    ),
                    "08F03-S02-180K": None,
                    "31206-P3F-003": None,
                    "74100-S2A-010": None,
                },
            ),
            (
                CmsClient(),
                {
                    "12251-RBB-004": Stock(
                        available=False,
                        reference="12251-RBB-004",
                        price=Money(amount="106.48", currency="EUR"),
                        title="Gasket Comp, Cyln",
                        discontinued=None,
                        image=None,
                        url="https://www.cmsnl.com/products/gasket-compcyln_12251rbb004/",
                        country="NL",
                        source=SOURCE_CMS,
                    ),
                    "56483-PND-003": Stock(
                        available=False,
                        reference="56483-PND-003",
                        price=Money(amount="90.14", currency="EUR"),
                        title="Pulley Comp, P/s P",
                        discontinued=None,
                        image="https://images.cmsnl.com/img/partslists/ps-pump_medium00027665E__19_8e61.jpg",
                        url="https://www.cmsnl.com/products/pulley-compps-p_56483pnd003/",
                        country="NL",
                        source=SOURCE_CMS,
                    ),
                    "08F03-S02-180K": Stock(
                        available=False,
                        reference="08F03-S02-180K",
                        price=Money(amount="356.95", currency="EUR"),
                        title="Splr, Rr. *nh583m*",
                        discontinued=None,
                        image="https://images.cmsnl.com/img/partslists/accessories-exterior_medium00026365XEX01_4c21.jpg",
                        url="https://www.cmsnl.com/products/splrrr-nh583m_08f03s02180k/",
                        country="NL",
                        source=SOURCE_CMS,
                    ),
                    "31206-P3F-003": Stock(
                        available=False,
                        reference="31206-P3F-003",
                        price=Money(amount="413.82", currency="EUR"),
                        title="Armature Comp",
                        discontinued=None,
                        image="https://images.cmsnl.com/img/partslists/starter-motor-denso_medium00026534E__0710_24f7.jpg",
                        url="https://www.cmsnl.com/products/armature-comp_31206p3f003/",
                        country="NL",
                        source=SOURCE_CMS,
                    ),
                    "74100-S2A-010": Stock(
                        reference="74100-S2A-010",
                        url="https://www.cmsnl.com/products/fender-assy-rfr_74100s2a010/",
                        source=SOURCE_CMS,
                        country="NL",
                        title="Fender Assy R, Fr",
                        price=Money(amount="183.92", currency="EUR"),
                        image=None,
                        available=False,
                        discontinued=None,
                        quantity=None,
                    ),
                },
            ),
            (
                NengunClient(),
                {
                    "12251-RBB-004": None,
                    "56483-PND-003": None,
                    "08F03-S02-180K": None,
                    "31206-P3F-003": None,
                    "74100-S2A-010": Stock(
                        reference="74100-S2A-010",
                        url="https://www.nengun.com/oem/honda/74100-s2a-010",
                        source=SOURCE_NENGUN,
                        country="JP",
                        title="FENDER ASSY., R. FR. INNER",
                        price=Money(amount=72.28, currency="EUR"),
                        image="https://image.nengun.com/brand/product/nengun-537-honda.png",
                        available=True,
                        discontinued=None,
                        quantity=None,
                    ),
                },
            ),
            (
                AkrClient(),
                {
                    "12251-RBB-004": Stock(
                        reference="12251-RBB-004",
                        url="https://www.akr-performance.com/p/honda-cylinder-head-gasket-12251-rbb-004",
                        source=SOURCE_AKR,
                        country="NL",
                        title="Honda Cylinder head gasket",
                        price=Money(amount="116.80", currency="EUR"),
                        image="https://www.akr-performance.com/media/products/engine-parts-1-accord-4-door-sedan-2003-2005-24i_honda-cylinder-head-gasket-12251-rbb-004.jpg",
                        available=False,
                        discontinued=False,
                        quantity=None,
                    ),
                    "56483-PND-003": None,
                    "08F03-S02-180K": None,
                    "31206-P3F-003": None,
                    "74100-S2A-010": None,
                },
            ),
            (
                OnlineteileClient(),
                {
                    "12251-RBB-004": Stock(
                        reference="12251-RBB-004",
                        url="https://www.online-teile.com/honda-ersatzteile/12251RBB004_Gasket-Comp-Cylinder-He.html",
                        source=SOURCE_ONLINETEILE,
                        country="DE",
                        title="Gasket Comp Cylinder He",
                        price=Money("118.39", "EUR"),
                        image=None,
                        available=True,
                        discontinued=None,
                        quantity=None,
                    ),
                    "56483-PND-003": Stock(
                        reference="56483-PND-003",
                        url="https://www.online-teile.com/honda-ersatzteile/56483PND003_Pulley-Comp-Power-Steer.html",
                        source=SOURCE_ONLINETEILE,
                        country="DE",
                        title="Pulley Comp Power Steer",
                        price=Money("104.13", "EUR"),
                        image=None,
                        available=True,
                        discontinued=None,
                        quantity=None,
                    ),
                    "08F03-S02-180K": None,
                    "31206-P3F-003": None,
                    "74100-S2A-010": Stock(
                        reference="74100-S2A-010",
                        url="https://www.online-teile.com/honda-ersatzteile/74100S2A010_Fender-Assy-R-Fr-Inne.html",
                        source=SOURCE_ONLINETEILE,
                        country="DE",
                        title="Fender Assy R Fr Inne",
                        price=Money("218.1", "EUR"),
                        image=None,
                        available=True,
                        discontinued=None,
                        quantity=None,
                    ),
                },
            ),
        ),
    )
    async def test_success(self, client, expected):
        for reference in REFERENCES:
            assert await client.get_part(reference) == expected[reference]
