# Generated by Django 4.0.6 on 2022-07-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0002_rename_reference_stock_part_stock_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="source",
            field=models.CharField(
                choices=[("epc-data", "www.epc-data.com")], default="foo", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="source",
            field=models.CharField(
                choices=[
                    ("hondaautomotiveparts", "www.hondaautomotiveparts.com"),
                    ("hondapartsnow", "www.hondapartsnow.com"),
                    ("hondapartsonline", "www.hondapartsonline.net"),
                ],
                default="foo",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.URLField(default=None, unique=True),
        ),
    ]
