# Generated by Django 4.0.6 on 2022-07-28 21:43

from django.db import migrations, models

import part.validators


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0003_part_source_stock_source_alter_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="reference",
            field=models.CharField(
                default=None,
                max_length=13,
                unique=True,
                validators=[part.validators.validate_reference],
            ),
        ),
    ]
