# Generated by Django 4.0.6 on 2022-07-31 21:53

from django.db import migrations, models
import part.validators


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0005_alter_stock_options_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='reference',
            field=models.CharField(default=None, max_length=14, unique=True, validators=[part.validators.validate_reference]),
        ),
    ]
