# Generated by Django 4.0.6 on 2022-08-01 09:33

from django.db import migrations, models

import part.validators


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0006_alter_part_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="reference",
            field=models.CharField(
                default=None,
                max_length=15,
                unique=True,
                validators=[part.validators.validate_reference],
            ),
        ),
    ]
