# Generated by Django 4.0.6 on 2022-08-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0008_historicalstock_historicalpart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stock",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
