# Generated by Django 4.0.6 on 2022-08-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0009_alter_historicalstock_title_alter_stock_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstock",
            name="url",
            field=models.URLField(default="https://www.foo.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="url",
            field=models.URLField(default="https://www.foo.com"),
            preserve_default=False,
        ),
    ]
