# Generated by Django 4.0.6 on 2022-08-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0010_historicalstock_url_stock_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpart",
            name="source",
            field=models.CharField(
                choices=[
                    ("epc-data", "www.epc-data.com"),
                    ("amayama", "www.amayama.com"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="source",
            field=models.CharField(
                choices=[
                    ("epc-data", "www.epc-data.com"),
                    ("amayama", "www.amayama.com"),
                ],
                max_length=20,
            ),
        ),
    ]
