# Generated by Django 4.1 on 2022-08-12 21:53

import django_countries.fields
from django.db import migrations, models


def set_country(apps, schema_editor):
    Stock = apps.get_model("part", "Stock")
    for stock in Stock.objects.all():
        match stock.source:
            case "hondaautomotiveparts":
                stock.country = "US"
                stock.save()
            case "hondapartsnow":
                stock.country = "US"
                stock.save()
            case "hondapartsonline":
                stock.country = "US"
                stock.save()
            case "tegiwa":
                stock.country = "GB"
                stock.save()


def set_country_historical(apps, schema_editor):
    Stock = apps.get_model("part", "Historicalstock")
    for stock in Stock.objects.all():
        match stock.source:
            case "hondaautomotiveparts":
                stock.country = "US"
                stock.save()
            case "hondapartsnow":
                stock.country = "US"
                stock.save()
            case "hondapartsonline":
                stock.country = "US"
                stock.save()
            case "tegiwa":
                stock.country = "GB"
                stock.save()


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0012_alter_historicalstock_source_alter_stock_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="stock",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.RunPython(set_country_historical, migrations.RunPython.noop),
        migrations.RunPython(set_country, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="stock",
            name="country",
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="country",
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="source",
            field=models.CharField(
                choices=[
                    ("hondaautomotiveparts", "www.hondaautomotiveparts.com"),
                    ("hondapartsnow", "www.hondapartsnow.com"),
                    ("hondapartsonline", "www.hondapartsonline.net"),
                    ("tegiwa", "www.tegiwaimports.com"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="source",
            field=models.CharField(
                choices=[
                    ("hondaautomotiveparts", "www.hondaautomotiveparts.com"),
                    ("hondapartsnow", "www.hondapartsnow.com"),
                    ("hondapartsonline", "www.hondapartsonline.net"),
                    ("tegiwa", "www.tegiwaimports.com"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("part", "source", "country")},
        ),
    ]
