# Generated by Django 4.1 on 2022-08-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0013_alter_stock_unique_together_historicalstock_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpart",
            name="source",
            field=models.CharField(
                choices=[
                    ("epc-data", "www.epc-data.com"),
                    ("amayama", "www.amayama.com"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="source",
            field=models.CharField(
                choices=[
                    ("epc-data", "www.epc-data.com"),
                    ("amayama", "www.amayama.com"),
                ],
                max_length=8,
            ),
        ),
    ]
