# Generated by Django 4.1 on 2022-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0017_alter_historicalstock_source_alter_stock_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpart",
            name="source",
            field=models.CharField(
                choices=[
                    ("epc-data", "www.epc-data.com"),
                    ("amayama", "www.amayama.com"),
                    ("clockwise-motion", "www.clockwisemotion.co.uk"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="source",
            field=models.CharField(
                choices=[
                    ("epc-data", "www.epc-data.com"),
                    ("amayama", "www.amayama.com"),
                    ("clockwise-motion", "www.clockwisemotion.co.uk"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
    ]
