# Generated by Django 4.1 on 2022-09-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0025_alter_historicalstock_source_alter_stock_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.URLField(default=None, max_length=300, unique=True),
        ),
    ]
