# Generated by Django 4.1.3 on 2023-07-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0001_squashed_0041_alter_historicalstock_title_alter_stock_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="stock",
            name="url",
            field=models.URLField(),
        ),
    ]
