# Generated by Django 4.1.3 on 2023-09-06 19:14

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0045_alter_historicalstock_source_alter_stock_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name="stock",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
