# Generated by Django 4.1.3 on 2023-09-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0046_alter_historicalstock_country_alter_stock_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpart",
            name="last_time_delivered",
            field=models.DateTimeField(
                help_text="last time when this part has been delivered to a scraper",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="last_time_delivered",
            field=models.DateTimeField(
                help_text="last time when this part has been delivered to a scraper",
                null=True,
            ),
        ),
    ]
