# Generated by Django 4.1.3 on 2023-10-18 18:11

from django.db import migrations, models


def fill_many_to_many_relationship(apps, schema_editor):
    Image = apps.get_model("part", "Image")

    for image in Image.objects.all():
        image.stocks.add(image.stock)


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0047_historicalpart_last_time_delivered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="stocks",
            field=models.ManyToManyField(related_name="stocks", to="part.stock"),
        ),
        migrations.RunPython(fill_many_to_many_relationship),
    ]
