# Generated by Django 4.1.3 on 2023-11-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0050_stock_changed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="title",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="stock",
            name="title",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
