# Generated by Django 4.1.3 on 2023-12-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0058_alter_historicalstock_source_alter_stock_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="source",
            field=models.CharField(
                choices=[
                    ("hondaautomotiveparts", "www.hondaautomotiveparts.com"),
                    ("hondapartsnow", "www.hondapartsnow.com"),
                    ("hondapartsonline", "www.hondapartsonline.net"),
                    ("tegiwa", "www.tegiwaimports.com"),
                    ("amayama", "www.amayama.com"),
                    ("clockwise-motion", "www.clockwisemotion.co.uk"),
                    ("hondaspareparts", "www.hondaspareparts.co.uk"),
                    ("pieces-auto-honda", "www.pieces-auto-honda.fr"),
                    ("acuraexpressparts", "www.acuraexpressparts.com"),
                    ("acurapartsforless", "www.acurapartsforless.com"),
                    ("all4honda", "www.a4h-tech.com"),
                    ("cms", "www.cmsnl.com"),
                    ("nengun", "www.nengun.com"),
                    ("akr", "www.akr-performance.com"),
                    ("online-teile", "www.online-teile.com"),
                    ("japserviceparts", "www.japserviceparts.co.uk"),
                    ("icb", "www.icbmotorsport.com"),
                    ("ipgparts", "www.ipgparts.com"),
                    ("bernardiparts", "www.bernardiparts.com"),
                    ("alvadi", "www.alvadi.ee"),
                    ("rywerksparts", "www.rywerksparts.com"),
                    ("myhondaoemparts", "www.myhondaoemparts.com"),
                    ("hondapartsforless", "www.hondapartsforless.com"),
                    ("oemhondapartswarehouse", "www.oemhondapartswarehouse.com"),
                    ("hondapartsconnection", "www.hondapartsconnection.com"),
                    ("desertcart", "www.desertcart.ae"),
                    ("coxmotorparts", "www.coxmotorparts.co.uk"),
                    ("dreamshop-airport-honda", "dreamshop.honda.com - Airport Honda"),
                    (
                        "dreamshop-airport-marina-honda",
                        "dreamshop.honda.com - Airport Marina Honda",
                    ),
                    (
                        "dreamshop-all-star-honda",
                        "dreamshop.honda.com - All Star Honda",
                    ),
                    (
                        "dreamshop-anderson-honda",
                        "dreamshop.honda.com - Anderson Honda",
                    ),
                    (
                        "dreamshop-antrim-way-honda",
                        "dreamshop.honda.com - Antrim Way Honda",
                    ),
                    ("dreamshop-apple-honda", "dreamshop.honda.com - Apple Honda"),
                    (
                        "dreamshop-apple-tree-honda",
                        "dreamshop.honda.com - Apple Tree Honda",
                    ),
                    (
                        "dreamshop-apple-valley-honda",
                        "dreamshop.honda.com - Apple Valley Honda",
                    ),
                    (
                        "dreamshop-arrowhead-honda",
                        "dreamshop.honda.com - Arrowhead Honda",
                    ),
                    (
                        "dreamshop-ascension-honda",
                        "dreamshop.honda.com - Ascension Honda",
                    ),
                    ("dreamshop-atamian-honda", "dreamshop.honda.com - Atamian Honda"),
                    (
                        "dreamshop-atlantic-honda",
                        "dreamshop.honda.com - Atlantic Honda",
                    ),
                    ("dreamshop-auburn-honda", "dreamshop.honda.com - Auburn Honda"),
                    (
                        "dreamshop-autonation-honda-104",
                        "dreamshop.honda.com - AutoNation Honda 104",
                    ),
                    (
                        "dreamshop-autonation-honda-385",
                        "dreamshop.honda.com - AutoNation Honda 385",
                    ),
                    (
                        "dreamshop-autonation-honda-bel-air-mall",
                        "dreamshop.honda.com - AutoNation Honda at Bel Air Mall",
                    ),
                    (
                        "dreamshop-autonation-honda-chandler",
                        "dreamshop.honda.com - AutoNation Honda Chandler",
                    ),
                    (
                        "dreamshop-autonation-honda-clearwater",
                        "dreamshop.honda.com - AutoNation Honda Clearwater",
                    ),
                    (
                        "dreamshop-autonation-honda-columbus",
                        "dreamshop.honda.com - AutoNation Honda Columbus",
                    ),
                    (
                        "dreamshop-autonation-honda-costa-mesa",
                        "dreamshop.honda.com - AutoNation Honda Costa Mesa",
                    ),
                    (
                        "dreamshop-autonation-covington-pike",
                        "dreamshop.honda.com - AutoNation Honda Covington Pike",
                    ),
                    ("dreamshop-barber-honda", "dreamshop.honda.com - Barber Honda"),
                    (
                        "dreamshop-barbour-hendrick-honda-greenville",
                        "dreamshop.honda.com - Barbour Hendrick Honda Greenville",
                    ),
                    ("dreamshop-barker-honda", "dreamshop.honda.com - Barker Honda"),
                    ("dreamshop-baron-honda", "dreamshop.honda.com - Baron Honda"),
                    (
                        "dreamshop-battison-honda",
                        "dreamshop.honda.com - Battison Honda",
                    ),
                    (
                        "dreamshop-battle-creek-honda",
                        "dreamshop.honda.com - Battle Creek Honda",
                    ),
                    (
                        "dreamshop-bay-ridge-honda",
                        "dreamshop.honda.com - Bay Ridge Honda",
                    ),
                    (
                        "dreamshop-bedard-bros-honda",
                        "dreamshop.honda.com - Bedard Bros. Honda",
                    ),
                    ("dreamshop-bell-honda", "dreamshop.honda.com - Bell Honda"),
                    ("dreamshop-bend-honda", "dreamshop.honda.com - Bend Honda"),
                    (
                        "dreamshop-berkeley-honda-autocenter",
                        "dreamshop.honda.com - Berkeley Honda Autocenter",
                    ),
                    (
                        "dreamshop-berlin-city-honda-of-portland",
                        "dreamshop.honda.com - Berlin City Honda of Portland",
                    ),
                    (
                        "dreamshop-big-star-honda",
                        "dreamshop.honda.com - Big Star Honda",
                    ),
                    (
                        "dreamshop-bill-page-honda",
                        "dreamshop.honda.com - Bill Page Honda",
                    ),
                    (
                        "dreamshop-bill-pearce-courtesy-honda",
                        "dreamshop.honda.com - Bill Pearce Courtesy Honda",
                    ),
                    (
                        "dreamshop-bommarito-honda-superstore",
                        "dreamshop.honda.com - Bommarito Honda Superstore",
                    ),
                    ("dreamshop-braman-honda", "dreamshop.honda.com - Braman Honda"),
                    (
                        "dreamshop-braman-honda-of-palm-beach",
                        "dreamshop.honda.com - Braman Honda of Palm Beach",
                    ),
                    (
                        "dreamshop-autonation-honda-south-corpus-christi",
                        "dreamshop.honda.com - AutoNation Honda South Corpus Christi",
                    ),
                    (
                        "dreamshop-autonation-honda-tucson-auto-mall",
                        "dreamshop.honda.com - AutoNation Honda Tucson Auto Mall",
                    ),
                    (
                        "dreamshop-autonation-honda-valencia",
                        "dreamshop.honda.com - AutoNation Honda Valencia",
                    ),
                    (
                        "dreamshop-brilliance-honda-of-crystal-lake",
                        "dreamshop.honda.com - Brilliance Honda of Crystal Lake",
                    ),
                    (
                        "dreamshop-canobie-lake-honda",
                        "dreamshop.honda.com - Canobie Lake Honda",
                    ),
                    (
                        "dreamshop-cape-girardeau-honda",
                        "dreamshop.honda.com - Cape Girardeau Honda",
                    ),
                    (
                        "dreamshop-capital-city-honda",
                        "dreamshop.honda.com - Capital City Honda",
                    ),
                    ("dreamshop-capital-honda", "dreamshop.honda.com - Capital Honda"),
                ],
                db_index=True,
                max_length=47,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="source",
            field=models.CharField(
                choices=[
                    ("hondaautomotiveparts", "www.hondaautomotiveparts.com"),
                    ("hondapartsnow", "www.hondapartsnow.com"),
                    ("hondapartsonline", "www.hondapartsonline.net"),
                    ("tegiwa", "www.tegiwaimports.com"),
                    ("amayama", "www.amayama.com"),
                    ("clockwise-motion", "www.clockwisemotion.co.uk"),
                    ("hondaspareparts", "www.hondaspareparts.co.uk"),
                    ("pieces-auto-honda", "www.pieces-auto-honda.fr"),
                    ("acuraexpressparts", "www.acuraexpressparts.com"),
                    ("acurapartsforless", "www.acurapartsforless.com"),
                    ("all4honda", "www.a4h-tech.com"),
                    ("cms", "www.cmsnl.com"),
                    ("nengun", "www.nengun.com"),
                    ("akr", "www.akr-performance.com"),
                    ("online-teile", "www.online-teile.com"),
                    ("japserviceparts", "www.japserviceparts.co.uk"),
                    ("icb", "www.icbmotorsport.com"),
                    ("ipgparts", "www.ipgparts.com"),
                    ("bernardiparts", "www.bernardiparts.com"),
                    ("alvadi", "www.alvadi.ee"),
                    ("rywerksparts", "www.rywerksparts.com"),
                    ("myhondaoemparts", "www.myhondaoemparts.com"),
                    ("hondapartsforless", "www.hondapartsforless.com"),
                    ("oemhondapartswarehouse", "www.oemhondapartswarehouse.com"),
                    ("hondapartsconnection", "www.hondapartsconnection.com"),
                    ("desertcart", "www.desertcart.ae"),
                    ("coxmotorparts", "www.coxmotorparts.co.uk"),
                    ("dreamshop-airport-honda", "dreamshop.honda.com - Airport Honda"),
                    (
                        "dreamshop-airport-marina-honda",
                        "dreamshop.honda.com - Airport Marina Honda",
                    ),
                    (
                        "dreamshop-all-star-honda",
                        "dreamshop.honda.com - All Star Honda",
                    ),
                    (
                        "dreamshop-anderson-honda",
                        "dreamshop.honda.com - Anderson Honda",
                    ),
                    (
                        "dreamshop-antrim-way-honda",
                        "dreamshop.honda.com - Antrim Way Honda",
                    ),
                    ("dreamshop-apple-honda", "dreamshop.honda.com - Apple Honda"),
                    (
                        "dreamshop-apple-tree-honda",
                        "dreamshop.honda.com - Apple Tree Honda",
                    ),
                    (
                        "dreamshop-apple-valley-honda",
                        "dreamshop.honda.com - Apple Valley Honda",
                    ),
                    (
                        "dreamshop-arrowhead-honda",
                        "dreamshop.honda.com - Arrowhead Honda",
                    ),
                    (
                        "dreamshop-ascension-honda",
                        "dreamshop.honda.com - Ascension Honda",
                    ),
                    ("dreamshop-atamian-honda", "dreamshop.honda.com - Atamian Honda"),
                    (
                        "dreamshop-atlantic-honda",
                        "dreamshop.honda.com - Atlantic Honda",
                    ),
                    ("dreamshop-auburn-honda", "dreamshop.honda.com - Auburn Honda"),
                    (
                        "dreamshop-autonation-honda-104",
                        "dreamshop.honda.com - AutoNation Honda 104",
                    ),
                    (
                        "dreamshop-autonation-honda-385",
                        "dreamshop.honda.com - AutoNation Honda 385",
                    ),
                    (
                        "dreamshop-autonation-honda-bel-air-mall",
                        "dreamshop.honda.com - AutoNation Honda at Bel Air Mall",
                    ),
                    (
                        "dreamshop-autonation-honda-chandler",
                        "dreamshop.honda.com - AutoNation Honda Chandler",
                    ),
                    (
                        "dreamshop-autonation-honda-clearwater",
                        "dreamshop.honda.com - AutoNation Honda Clearwater",
                    ),
                    (
                        "dreamshop-autonation-honda-columbus",
                        "dreamshop.honda.com - AutoNation Honda Columbus",
                    ),
                    (
                        "dreamshop-autonation-honda-costa-mesa",
                        "dreamshop.honda.com - AutoNation Honda Costa Mesa",
                    ),
                    (
                        "dreamshop-autonation-covington-pike",
                        "dreamshop.honda.com - AutoNation Honda Covington Pike",
                    ),
                    ("dreamshop-barber-honda", "dreamshop.honda.com - Barber Honda"),
                    (
                        "dreamshop-barbour-hendrick-honda-greenville",
                        "dreamshop.honda.com - Barbour Hendrick Honda Greenville",
                    ),
                    ("dreamshop-barker-honda", "dreamshop.honda.com - Barker Honda"),
                    ("dreamshop-baron-honda", "dreamshop.honda.com - Baron Honda"),
                    (
                        "dreamshop-battison-honda",
                        "dreamshop.honda.com - Battison Honda",
                    ),
                    (
                        "dreamshop-battle-creek-honda",
                        "dreamshop.honda.com - Battle Creek Honda",
                    ),
                    (
                        "dreamshop-bay-ridge-honda",
                        "dreamshop.honda.com - Bay Ridge Honda",
                    ),
                    (
                        "dreamshop-bedard-bros-honda",
                        "dreamshop.honda.com - Bedard Bros. Honda",
                    ),
                    ("dreamshop-bell-honda", "dreamshop.honda.com - Bell Honda"),
                    ("dreamshop-bend-honda", "dreamshop.honda.com - Bend Honda"),
                    (
                        "dreamshop-berkeley-honda-autocenter",
                        "dreamshop.honda.com - Berkeley Honda Autocenter",
                    ),
                    (
                        "dreamshop-berlin-city-honda-of-portland",
                        "dreamshop.honda.com - Berlin City Honda of Portland",
                    ),
                    (
                        "dreamshop-big-star-honda",
                        "dreamshop.honda.com - Big Star Honda",
                    ),
                    (
                        "dreamshop-bill-page-honda",
                        "dreamshop.honda.com - Bill Page Honda",
                    ),
                    (
                        "dreamshop-bill-pearce-courtesy-honda",
                        "dreamshop.honda.com - Bill Pearce Courtesy Honda",
                    ),
                    (
                        "dreamshop-bommarito-honda-superstore",
                        "dreamshop.honda.com - Bommarito Honda Superstore",
                    ),
                    ("dreamshop-braman-honda", "dreamshop.honda.com - Braman Honda"),
                    (
                        "dreamshop-braman-honda-of-palm-beach",
                        "dreamshop.honda.com - Braman Honda of Palm Beach",
                    ),
                    (
                        "dreamshop-autonation-honda-south-corpus-christi",
                        "dreamshop.honda.com - AutoNation Honda South Corpus Christi",
                    ),
                    (
                        "dreamshop-autonation-honda-tucson-auto-mall",
                        "dreamshop.honda.com - AutoNation Honda Tucson Auto Mall",
                    ),
                    (
                        "dreamshop-autonation-honda-valencia",
                        "dreamshop.honda.com - AutoNation Honda Valencia",
                    ),
                    (
                        "dreamshop-brilliance-honda-of-crystal-lake",
                        "dreamshop.honda.com - Brilliance Honda of Crystal Lake",
                    ),
                    (
                        "dreamshop-canobie-lake-honda",
                        "dreamshop.honda.com - Canobie Lake Honda",
                    ),
                    (
                        "dreamshop-cape-girardeau-honda",
                        "dreamshop.honda.com - Cape Girardeau Honda",
                    ),
                    (
                        "dreamshop-capital-city-honda",
                        "dreamshop.honda.com - Capital City Honda",
                    ),
                    ("dreamshop-capital-honda", "dreamshop.honda.com - Capital Honda"),
                ],
                db_index=True,
                max_length=47,
            ),
        ),
    ]
