# Generated by Django 5.0.1 on 2024-01-17 18:31

from django.db import migrations, models

import part.validators


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0063_alter_historicalstock_price_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpart",
            name="reference",
            field=models.CharField(
                db_index=True,
                default=None,
                max_length=15,
                validators=[
                    part.validators.validate_reference,
                    part.validators.validate_empty,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="reference",
            field=models.CharField(
                default=None,
                max_length=15,
                unique=True,
                validators=[
                    part.validators.validate_reference,
                    part.validators.validate_empty,
                ],
            ),
        ),
    ]
