# Generated by Django 5.0.1 on 2024-02-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0064_alter_historicalpart_reference_alter_part_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="title",
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="stock",
            name="title",
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
