# Generated by Django 5.0.1 on 2024-01-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewpart",
            name="source",
            field=models.CharField(default="foo", max_length=30),
            preserve_default=False,
        ),
    ]
